# Generated by Django 5.0.6 on 2024-07-05 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='schudlematch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_team', models.DecimalField(decimal_places=0, max_digits=5)),
                ('second_team', models.DecimalField(decimal_places=0, max_digits=5)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S_L_M.schudlematch')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Name', models.CharField(max_length=10)),
                ('Team_city', models.CharField(max_length=15)),
                ('Team_coach', models.CharField(max_length=15)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='schudlematch',
            name='First_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='First_team', to='S_L_M.team'),
        ),
        migrations.AddField(
            model_name='schudlematch',
            name='Second_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='S_L_M.team'),
        ),
        migrations.CreateModel(
            name='winmatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Win_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S_L_M.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S_L_M.schudlematch')),
            ],
        ),
    ]
