# Generated by Django 5.0.6 on 2024-07-05 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_L_M', '0002_winmatch_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winmatch',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='score',
            name='timestamp',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
